name: pnpm

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello environment"

      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        with:
          node-version: "22"
