name: pnpm

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - id: my-step-output
        run: |
          echo "text=hi from ${{ runner.os }}" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.my-step-output.outputs.text }}"
