on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Qaysi muhit?"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

      tag:
        description: "Git tag"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploy to ${{ github.event.inputs.environment }}"
      # - run: echo "Tag: ${{ github.event.inputs.tag }}"
