name: Learn

on:
  push:

jobs:
  setup_node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

        with:
          node-version: "22"

      - run: ls -la

      - working-directory: ./test
        run: ls -la

      - run: node -v

      - run: npm -v
