name: Parallel jobs

on:
  push:
    branches: [workflow-planner]

jobs:
  job1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22, 23]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: console.log("Hello from node-${{ matrix.node-version }}");
