name: Parallel jobs

on:
  push:
    branches: [workflow-planner]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - run: ls -la

      - run: touch ${{ github.workspace }}/test.txt

      - run: ls -la

      - run: la -la ${{ github.workspace }}
