name: "Sevices: Postgres"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - run: |
          sudo apt-get updates
          sudo apt-get install -y postgresql-client

      - run: psql -h postgres -U postgres -c "SELECT 1"
        env:
          PGPASSWORD: postgres
